GET http://localhost:8000/api/v1/stores HTTP/1.1

###

POST http://localhost:8000/api/v1/stores HTTP/1.1
Content-Type: application/json

{
	"storeId": "0001",
	"address": "10 Main St. Haverhill MA"
}

###

POST http://localhost:8000/api/v1/stores HTTP/1.1
Content-Type: application/json

{
	"storeId": "0002",
	"address": "10 Main St. Lawrence MA"
}

###

GET http://localhost:8000/api/v1/users HTTP/1.1

###

POST http://localhost:8000/api/v1/users HTTP/1.1
Content-Type: application/json

{
	"email": "test3@test.com",
	"password": "password123"
}

###

GET http://localhost:8000/api/v1/users/5f1efc3c3bfb4a1744a093a5 HTTP/1.1

###

PUT http://localhost:8000/api/v1/users/5f1efc3c3bfb4a1744a093a5 HTTP/1.1
Content-Type: application/json

{
	"email": "a123456@test.com"
}

###

DELETE http://localhost:8000/api/v1/users/5f1ef5900eaf332d2ce56d5b HTTP/1.1
